### ISSUE TITLE
clock-app does not have a maintainer

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/clock-app#1]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Clocking in a great resume builder (I don't have many puns regarding clocks.)

**Comment by dark-eye** [comment]
Hey,

Can i take that on?
I had a few improvements to the clock when it was on launch pad which  never came in. 
And I would like to share them, and help UBports  in any way i can...

Thanks,

**Comment by Flohack74** [comment]
Yeah sure, very welcome!

If you need old / MR branches from LP, tell me, I can import them. Then you can work from there. Please also merge as much as possible pending MRs in LP.

BR

**Comment by Flohack74** [comment]
OK saw your PR just now - is it ok to ontinue working on master? I think clock-app anyway had not so many branches :) So I am merging this right away...

BR

**Comment by dark-eye** [comment]
Hehe most of those MR's  are mine :) 
I`ll merge the testability as fast as I can and cancel mine as I would like to make their code a little cleaner.

**Comment by Flohack74** [comment]
I´ll close this issue ;)
