### ISSUE TITLE
Alarms not displayed

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/clock-app#102]
After xenial update to RC v13 from September 26, alarms are not displayed anymore. If I create a new alarm then that is not displayed either but it will ring. I can find that new created alarm and the previous alarms with `syncevolution --print-items backend=evolution-tasks database=1475229594.5479.0@ubuntu-phablet` but I have to mention that 1475229594.5479.0@ubuntu-phablet is not the default database in evolution-tasks.

**Comment by dark-eye** [comment]
@mihaelmilea Hmm you might have found the issue that caused alarms and calendar sync to break :+1: The missing alarms issue it should be fixed in the current 16.04/dev  r172.

**Comment by mihaelmilea** [comment]
So if I switch from rc to devel channel it should work?

**Comment by dark-eye** [comment]
Yes works for me :)

**Comment by ruedigerkupper** [comment]
Confirming problem on RC channel. Not brave enough to switch to devel... When will it land in RC?

**Comment by mihaelmilea** [comment]
It is now in rc v14.
