### ISSUE TITLE
Get tranlsation generation to work as it seem to fail currently.

### ISSUE THREAD

**Issue by dark-eye** [ubports/clock-app#20]
REsult  of the  command that should  build the translation files :
$ click-buddy --dir . --no-clean

bzr: ERROR: Not a branch: "/home/eran/projects/oss/Ubuntu/github/clock-app/".
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:18 (find_package):
  By not providing "FindQt5Qml.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Qml", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Qml" with any
  of the following names:

    Qt5QmlConfig.cmake
    qt5qml-config.cmake

  Add the installation prefix of "Qt5Qml" to CMAKE_PREFIX_PATH or set
  "Qt5Qml_DIR" to a directory containing one of the above files.  If "Qt5Qml"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Warning at CMakeLists.txt:19 (find_package):
  By not providing "FindQt5Quick.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Quick",
  but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Quick" with any
  of the following names:

    Qt5QuickConfig.cmake
    qt5quick-config.cmake

  Add the installation prefix of "Qt5Quick" to CMAKE_PREFIX_PATH or set
  "Qt5Quick_DIR" to a directory containing one of the above files.  If
  "Qt5Quick" provides a separate development package or SDK, be sure it has
  been installed.

bzr: ERROR: Not a branch: "/home/eran/projects/oss/Ubuntu/github/clock-app/".
-- Setting BZR_SOURCE to lp:ubuntu-clock-app
-- Configuring manifest.json
CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreMacros.cmake:326 (find_package):
  Could not find a package configuration file provided by "Qt5Qml" with any
  of the following names:

    Qt5QmlConfig.cmake
    qt5qml-config.cmake

  Add the installation prefix of "Qt5Qml" to CMAKE_PREFIX_PATH or set
  "Qt5Qml_DIR" to a directory containing one of the above files.  If "Qt5Qml"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  backend/CMakeLists.txt:59 (qt5_use_modules)

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreMacros.cmake:328 (message):
  Can not use "Qml" module which has not yet been found.
Call Stack (most recent call first):
  backend/CMakeLists.txt:59 (qt5_use_modules)

-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.5Sx8YE1uj3/CMakeFiles/CMakeOutput.log".

**Comment by Flohack74** [comment]
Can you paste the error message etc. here?

**Comment by dark-eye** [comment]
Wow that was a fast response :)

**Comment by Flohack74** [comment]
Yeah just being online, playing with Jenkins and broke everything, so why not answer tickets xD
