### ISSUE TITLE
Added themes support

### ISSUE THREAD

**Issue by dark-eye** [ubports/clock-app#38]
When going to sleep sometimes it`s better to have a dark theme on the clock, so your spouse won't wake up when you set tomorrow alarm :)

**Comment by Flohack74** [comment]
This relates to https://github.com/ubports/ubports-touch/issues/191

**Comment by dark-eye** [comment]
@Flohack74 I basically just wanted to add support for the themes in the clock app and allow it  to follow the system theme too. 
The going to sleep issue was just an easy example as we have Suru Dark :)

**Comment by dark-eye** [comment]
**With SUru Dark  theme :**
(Sorry for all the RTL Hebrew text...)
![screenshot20170830_122317666](https://user-images.githubusercontent.com/1365484/29866700-e41c9152-8d81-11e7-8c0e-ce360da40a67.png)
![screenshot20170830_122319638](https://user-images.githubusercontent.com/1365484/29866704-e45fc3c8-8d81-11e7-8873-ccaf99be01ba.png)
![screenshot20170830_122322319](https://user-images.githubusercontent.com/1365484/29866701-e41d961a-8d81-11e7-8877-990d96a038b4.png)
![screenshot20170830_122327381](https://user-images.githubusercontent.com/1365484/29866702-e41e439e-8d81-11e7-9552-1fb2eb22e7b7.png)
![screenshot20170830_122331441](https://user-images.githubusercontent.com/1365484/29866703-e41f99f6-8d81-11e7-944f-e1a7469ee6bf.png)

**Comment by dark-eye** [comment]
It seems  that the bottom edge  doesn't like it`s theme  being changed.... working on it...
