### ISSUE TITLE
Can the alarms be sorted?

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/clock-app#47]
I have several alarms but they are not sorted by time. Can this be done?

- turbo, devel

**Comment by dark-eye** [comment]
Hey @mihaelmilea,

Thanks for opening an issue.
As far as i know currently it's sorted by the alarm closest to now to the farthest.

I did notice that there seem to be an issue when some of the alarms are disabled, I'll look in to it...

**Comment by mihaelmilea** [comment]
Oh, ok, I didn't think of that but it is true, two of my alarms are disabled and two are enabled. Their order is like this:
08:00 - disabled
08:30 - disabled
07:20 daily - enabled
08:30 on Sudays - enabled

So do you mean that this is what they are supposed to be sorted like? - if there is a logic to it I would be more than happy with that, I just didn't want them to be sorted in the order I created them or the be displayed in an order that I didn't understand.

Again, thank you for your response and your work and I am happy with the way it is if there is a logic to it - I will understand it and accept it!

**Comment by dark-eye** [comment]
I think there is an issue with disabled alarms as their next alarm date is frozen once disabled they will slowly bubble to the top of the list.

Logicly i think disabled alarms should be at the end of the list as you care about them the least.

**Comment by mihaelmilea** [comment]
It is true, the enabled alarms are sorted from the closest to the farthest in time. But the disabled alarms are not sorted, not even after days of being disabled:
![screenshot20171023_234256063](https://user-images.githubusercontent.com/30057613/32018087-6d9def0e-b9d1-11e7-8a29-77a1a8adb0ff.png)

**Comment by dark-eye** [comment]
Hey @mihaelmilea,

My guess it that the alarm are  sorted by the actual date the alarm was set to fire so the 8:00/8:30 arlarm in the  image above were probably disabled a day or  more before the  7:00/7:30.

In any case i`m currently working  on implementing a sorting logic in the clock app ,Currently it uses the  AlarmModel default sorting provided by the UITK.

**Comment by mihaelmilea** [comment]
Thank you @dark-eye for keeping this alive and continuing the work! Really thank you for any input and answer...

**Comment by the-Mitu** [comment]
How about ordering the alarms turned off always on the bottom?

I believe that ordering them by the next occurance is logical and I am for retaining this.
Actually do the "past" alarms exist? If they are repetitive, there is the next occurrance scheduled for the other day, so that's still in future and can be ordered among the rest of upcoming alarms. If the alarm is not repetitive, after ringing it will be switched off - therefore it should land on the bottom of the list (let's say because the next occurrance will never come as long as the alarm is off). These alarm on the bottom should be sorted by time regardless of the weekday - that's my suggestion.

**Comment by dark-eye** [comment]
I think this was the initial fix for this issue to bad telegram doesn't have a voting feature we could put this design decision crowd 😉
Currently the solution is held up as the behavior of the UI when sort is weird I might solve it by not updating the sort unless its the component creation or appeared is switched.

**Comment by mihaelmilea** [comment]
This seems to be fixed in rc v14 so I'm closing it. Many, many thanks to the developers!
