### ISSUE TITLE
 Alarms get set at wrong times after travelling

### ISSUE THREAD

**Issue by dark-eye** [ubports/clock-app#5]
**This is a duplication of the issue from LP at : https://bugs.launchpad.net/ubuntu-clock-app/+bug/1480546**

User impact: alarm will fail to ring at time set by user.

This might be the same issue as bug 1470320 but I don't feel that report is clear enough to be sure. My use case is:

1. Set an alarm to 9am (and leave clock app running).
2. Travel across timezones.
3. Use the settings icon (top right) from the clock app and then "Change time and date" to enter system settings, and change the time zone to my new location
4. Switch back to clock app (swipe from right edge)
5. Press back to get back to the main screen
6. Swipe from bottom edge to view alarms
7. Note that the alarm still says 9am
8. Edit the alarm by touching it

Expected result: the alarm time picker starts off at 9am.

Actual result: the alarm time picker starts off at 3am (or whatever the time zone difference is presumably)

9. Change alarm time to 10am
10. Touch the tick on the top right

Expected result: the alarm page now shows the alarm set at 10am, and an alarm is set to 10am in the date/time indicator.
Actual result: the alarm page now shows the alarm set at 4pm, and an alarm is set for 4pm in the date/time indicator.

It seems to me that if the timezone is changed while the clock app is running, then the alarm edit UI page screws up by offsetting anything displayed or set by the timezone difference. This will cause the user to inadvertently set an alarm to ring at the wrong time after having set the timezone correctly.

**Comment by Flohack74** [comment]
Lets pass this through CI and let it end up in the devel image, then we can test it. Currently CI is still pending as many core Apps need dependencies set up in the Jenkins server, some of them even conflicting other parts. This will get interesting ;)

**Comment by dark-eye** [comment]
Great! love CI.
Was about to ask if I need to upload it to open store  or will you guys do it :) 
if you need any help with the CI configuration i`m also  available  do my knowledge on Jenkins  is limited...

**Comment by Flohack74** [comment]
Basically it is a core app, plus in this case it is a deb packaging, can it be? Deb update will work only with our system image server.

**Comment by dark-eye** [comment]
It  think it  also have a click configuration and  snap configuration  (though i couldn't it get running).
I also just notice that a lot the tests fail... i think i`ll open an issue about it.

**Comment by dark-eye** [comment]
@Flohack74  Just read the the development blog post, do you need me to do anything for the CI to run?

**Comment by Flohack74** [comment]
Yeah ping me on Telegram during the next days. We need to find a pipeline for all core apps soon
