### ISSUE TITLE
Unable to save alarm settings

### ISSUE THREAD

**Issue by Fazarel** [ubports/clock-app#61]
On Nexus 5 OTA3, devel and RC (r23) channels : alarm doesn't save settings (Activation, Repeat, Sound).
Luckyly the alarm rings in the morning ! But with default sound and I have to set it every night.

**Comment by dark-eye** [comment]
Hey@fazarel

 Hmmm this is a weird one... 
does it happen on newly created alarms? can you send a log link (using the logviewer app) of the clock log just after you edited and saved an alarm?

thanks for reporting :)

**Comment by Fazarel** [comment]
Yesterday I tried and still didn't work, even with new alarm. Here is the log : https://paste.ubuntu.com/26379681/

Today I can save the settings. I don't know what changed. The new log :  https://paste.ubuntu.com/26388142/

I don't understand, but problem gone...

**Comment by dark-eye** [comment]
@Fazarel I also don't understand :( and the logs seems quite identical (in tier problems) please tell me if this issue returns.

Thanks,

**Comment by Fazarel** [comment]
I must have done something wrong... thanks for the help.
