### ISSUE TITLE
UBports 16.04 after application start - crash

### ISSUE THREAD

**Issue by bedna-KU** [ubports/clock-app#70]
Clock start and after 1-2 seconds crash

ubuntu-clock-app-3.8+0\~xenial20180318163247.33~1.gbp7d8719.armhf

HW: Nexus 4

Log: [logcat.txt](https://github.com/ubports/clock-app/files/1829235/logcat.txt)

**Comment by nfsprodriver** [comment]
fixed

**Comment by Flohack74** [comment]
Fixed but how?

**Comment by nfsprodriver** [comment]
Sorry, see https://github.com/ubports/ubuntu-touch/issues/705 ;)
