### ISSUE TITLE
Deleting alarm doesn't leave alarm creation view

### ISSUE THREAD

**Issue by Arc676** [ubports/clock-app#98]
If you create an alarm then tap to edit and hit "delete alarm," the application doesn't navigate back to the alarm page. Instead, it stays on the information page for the alarm, as if there was no response. Tapping "back" to return manually *does* show that the alarm has indeed been deleted, but this should be automatic.

Nexus 5 (hammerhead), 16.04/devel.

**Comment by dark-eye** [comment]
@Arc676 WOW it does do that! thanks for reporting :)

 ill fix it as soon as I can.

**Comment by dark-eye** [comment]
Hmm there seems  to be some issues  with the alarms on 16.04  the reason this happens is that the cancel function works but  then the alarm is in error state as  can be seen by the log  below : 
`
qml: Alarm Model updated
qml: Alarm Model updated
qml: [ERROR]: Error saving alarm, code: undefined
`

This might be also related to : https://github.com/ubports/ubuntu-touch/issues/869

**Comment by Arc676** [comment]
Yup! Works on latest UT build and latest Clock version. Thanks!
